// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions 
(user_id, description, amount, ttype) 
VALUES ($1, $2, $3, $4)
`

type CreateTransactionParams struct {
	UserID      int32
	Description string
	Amount      int64
	Ttype       string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction,
		arg.UserID,
		arg.Description,
		arg.Amount,
		arg.Ttype,
	)
	return err
}

const getAllBalance = `-- name: GetAllBalance :many
SELECT
	u.id as user_id,
	u.name as user_name,
	u.balance_limit as limit,
	u.balance as balance,
	SUM(
		CASE WHEN t.ttype = 'c'
			THEN t.amount
		ELSE t.amount * -1
		END
	) AS sum_transactions,
	count(*) as transactions
FROM users u
	INNER JOIN transactions t
	ON u.id = t.user_id
GROUP BY
	u.id,
	u.balance_limit,
	u.balance
ORDER BY u.id
`

type GetAllBalanceRow struct {
	UserID          int32
	UserName        string
	Limit           int64
	Balance         int64
	SumTransactions int64
	Transactions    int64
}

func (q *Queries) GetAllBalance(ctx context.Context) ([]GetAllBalanceRow, error) {
	rows, err := q.db.Query(ctx, getAllBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBalanceRow
	for rows.Next() {
		var i GetAllBalanceRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.Limit,
			&i.Balance,
			&i.SumTransactions,
			&i.Transactions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByUser = `-- name: GetTransactionsByUser :many
SELECT t.description, t.amount, t.created_at, t.ttype
FROM transactions t
WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type GetTransactionsByUserParams struct {
	UserID int32
	Limit  int32
}

type GetTransactionsByUserRow struct {
	Description string
	Amount      int64
	CreatedAt   pgtype.Timestamp
	Ttype       string
}

func (q *Queries) GetTransactionsByUser(ctx context.Context, arg GetTransactionsByUserParams) ([]GetTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByUserRow
	for rows.Next() {
		var i GetTransactionsByUserRow
		if err := rows.Scan(
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
			&i.Ttype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, balance, balance_limit 
FROM users 
WHERE id = $1
`

type GetUserRow struct {
	ID           int32
	Balance      int64
	BalanceLimit int64
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Balance, &i.BalanceLimit)
	return i, err
}

const updateUserBalance = `-- name: UpdateUserBalance :one
UPDATE users 
SET balance = balance + $1 
WHERE id = $2 RETURNING balance, balance_limit
`

type UpdateUserBalanceParams struct {
	Balance int64
	ID      int32
}

type UpdateUserBalanceRow struct {
	Balance      int64
	BalanceLimit int64
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (UpdateUserBalanceRow, error) {
	row := q.db.QueryRow(ctx, updateUserBalance, arg.Balance, arg.ID)
	var i UpdateUserBalanceRow
	err := row.Scan(&i.Balance, &i.BalanceLimit)
	return i, err
}
